package com.pyrosandro.bds.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum BdsErrorConstants {

    DEVICE_ALREADY_EXISTS(2001),
    DEVICE_ID_PROVIDED_BY_CLIENT(2002),
    DEVICE_MISSING_INPUT_ID(2003),
    DEVICE_MISMATCHING_INPUT_ID(2004),
    DEVICE_NOT_FOUND(2005),
    DEVICE_IDENTIFIER_ALREADY_EXISTS(2006),
    USER_ALREADY_EXISTS(2007),
    DEVICE_IDENTIFIER_NOT_FOUND(2008),
    USER_ID_PROVIDED_BY_CLIENT(2009),
    USER_MISSING_INPUT_ID(2010),
    USER_MISMATCHING_INPUT_ID(2011),
    USER_NOT_FOUND(2012),
    USER_IDENTIFIER_ALREADY_EXISTS(2013),
    TEMPERATURE_NOT_FOUND(2014),
    TEMPERATURE_ID_PROVIDED_BY_CLIENT(2015),
    TEMPERATURE_MISSING_INPUT_ID(2016),
    TEMPERATURE_MISMATCHING_INPUT_ID(2017),
    ;

    public final int code;

}