## PROPS ##
SERVER_PORT: 8082
LOGGING_LEVEL: DEBUG

DATABASE_IP: localhost
DATABASE_PORT: 5434
DATABASE_NAME: dbBds
DATABASE_USERNAME: dbBds
DATABASE_PASSWORD: dbBds

SERVICE_REGISTRY_URL: localhost
SERVICE_REGISTRY_PORT: 8761
SERVICE_REGISTRY_USERNAME: eureka-user
SERVICE_REGISTRY_PASSWORD: eureka-pw

COMMON_PRINTSTACKTRACE: true
