## PROPS ##
SERVER_PORT: TBD
LOGGING_LEVEL: INFO

DATABASE_IP: TBD
DATABASE_PORT: TBD
DATABASE_NAME: TBD
DATABASE_USERNAME: TBD
DATABASE_PASSWORD: TBD

SERVICE_REGISTRY_URL: TBD
SERVICE_REGISTRY_PORT: TBD
SERVICE_REGISTRY_USERNAME: TBD
SERVICE_REGISTRY_PASSWORD: TBD

COMMON_PRINTSTACKTRACE: false